language: python
sudo: false
python:
  - "3.6.0"
install:
  - pip install -r requirements.txt
  - pip install nose
services:
script:
  - pytest
  - nosetests --exe -v
  - nosetests --exe --with-coverage --cover-package=app
after_success: coveralls
