language: python
python:
  - "3.6.0"

addons:
  apt:
    update: true
install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install pytest
services:
script:
  - pytest
  - nosetests --exe -v
  - nosetests --exe --with-coverage --cover-package=app
