language: python
python:
  - "3.6.0"

addons:
  apt:
    update: true
install:
  - pip install -r requirements.txt
script:
  - pytest
  - nosetests --exe -v
  - nosetests --exe --with-coverage --cover-package=app
  - coveralls

after_sucess:
  - "coveralls"