language: python
python:
  - "3.6.0"

addons:
  apt:
    update: true
install:
  - pip install -r requirements.txt
script:
  - pytest
  - nosetests --exe -v
  - nosetests --exe --with-coverage --cover-package=app
  - coveralls

services:
  - postgresql

before_script: 
  - psql -c "CREATE USER kzy;" 
  - psql -c 'CREATE DATABASE test_db;' -U kzy
  

after_sucess:
  - "coveralls"